# Generated by Django 3.2.4 on 2024-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='ddd', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='ddddd', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.BigIntegerField(default='8917247372', unique=True),
        ),
    ]
