# Generated by Django 3.2.4 on 2024-01-09 07:50

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240109_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='documents/pdf/sampleReport.pdf', upload_to=myapp.models.document_upload_path),
        ),
    ]
