# Generated by Django 3.2.4 on 2024-01-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20240109_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
    ]
